package com.demo.lifeconvenientdesign.Statistic;

import android.graphics.Color;

import java.util.ArrayList;
import java.util.List;

import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.AxisValue;
import lecho.lib.hellocharts.model.Column;
import lecho.lib.hellocharts.model.ColumnChartData;
import lecho.lib.hellocharts.model.SubcolumnValue;
import lecho.lib.hellocharts.view.ColumnChartView;

//工具类，设置对应的图表信息
public class ChartTool {
    private static String[] types={"餐饮","学习","其它"};
    List<String> title = new ArrayList<>();
    List<Integer> color = new ArrayList<>();
    //每各类型的总和
    float[] sums=new float[types.length];
    public void setSums(float[] sums){
        this.sums=sums;
    }

    private void initTitle(){
        for(String s:types){
            title.add(s);
        }
    }

    private void initColor(){
        color.add(Color.parseColor("#F36397"));
        color.add(Color.parseColor("#85B74F"));
        color.add(Color.parseColor("#ff0000"));
    }
    public void setChartViewData(ColumnChartView chart) {
        //底部标题
        initTitle();
        //颜色值
        initColor();
        //X轴值list
        List<AxisValue> axisXValues = new ArrayList<>();

        //所有的柱子
        List<Column> columns = new ArrayList<>();
        //单个柱子
        //Column column = new Column();

        //对每个集合的柱子进行遍历
        for (int i = 0; i < title.size(); i++) {
            //设置X轴的柱子所对应的属性名称(底部文字)
            axisXValues.add(new AxisValue(i).setLabel(title.get(i)));

            //对应的y轴数据
            List<SubcolumnValue> mPointValues = new ArrayList<>();
            mPointValues.add(new SubcolumnValue(sums[i],color.get(0)));

            //该类型的柱子设置
            Column column = new Column();
            column.setHasLabels(true);
            column.setHasLabelsOnlyForSelected(false);
            column.setValues(mPointValues);
            columns.add(column);
        }

        //设置Columns添加到Data中
        ColumnChartData columnData = new ColumnChartData(columns);

        //底部
        Axis axisBottom = new Axis(axisXValues);
        //是否显示X轴的网格线
        axisBottom.setHasLines(false);
        //分割线颜色
        axisBottom.setLineColor(Color.parseColor("#ff0000"));
        //字体颜色
        axisBottom.setTextColor(Color.parseColor("#666666"));
        //字体大小
        axisBottom.setTextSize(12);
        //底部文字
        axisBottom.setName("当月各类型支出统计");
        //每个柱子的便签是否倾斜着显示
        axisBottom.setHasTiltedLabels(false);
        //距离各标签之间的距离,包括离Y轴间距 (0-32之间)
        axisBottom.setMaxLabelChars(10);
        //设置是否自动生成轴对象,自动适应表格的范围(设置之后底部标题变成0-5)
        //axisBottom.setAutoGenerated(true);
        axisBottom.setHasSeparationLine(true);
        //设置x轴在底部显示
        columnData.setAxisXBottom(axisBottom);

        //左边  属性与上面一致
        Axis axisLeft = new Axis();
        axisLeft.setHasLines(false);
        axisLeft.setName("总支出");
        axisLeft.setHasTiltedLabels(true);
        axisLeft.setTextColor(Color.parseColor("#666666"));
        axisLeft.setTextSize(12);
        columnData.setAxisYLeft(axisLeft);

        //设置组与组之间的间隔比率,取值范围0-1,1表示组与组之间不留任何间隔
        columnData.setFillRatio(0.7f);
        chart.setInteractive(false);
        //最后将所有值显示在View中
        chart.setColumnChartData(columnData);
    }
}
